/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./resources/js/components/Common/Button.vue')['default']
    Card: typeof import('./resources/js/components/Common/Card.vue')['default']
    CardStatisticsHorizontal: typeof import('./resources/js/FMS/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./resources/js/FMS/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./resources/js/FMS/@core/components/cards/CardStatisticsWithImages.vue')['default']
    CivilServiceEligibility: typeof import('./resources/js/components/PDS/FormSections/CivilServiceEligibility.vue')['default']
    Dropdown: typeof import('./resources/js/components/Common/Dropdown.vue')['default']
    EducationBackground: typeof import('./resources/js/components/PDS/FormSections/EducationBackground.vue')['default']
    FamilyBackground: typeof import('./resources/js/components/PDS/FormSections/FamilyBackground.vue')['default']
    Form: typeof import('./resources/js/components/PDS/Form.vue')['default']
    Header: typeof import('./resources/js/components/Header/Header.vue')['default']
    Input: typeof import('./resources/js/components/Common/Input.vue')['default']
    Modal: typeof import('./resources/js/components/Common/Modal.vue')['default']
    MoreBtn: typeof import('./resources/js/FMS/@core/components/MoreBtn.vue')['default']
    Notification: typeof import('./resources/js/components/Common/Notification.vue')['default']
    OtherRelevantInfo: typeof import('./resources/js/components/PDS/FormSections/OtherRelevantInfo.vue')['default']
    Page1: typeof import('./resources/js/components/PDS/View/Pages/Page1.vue')['default']
    PDSFormModal: typeof import('./resources/js/components/PDS/PDSFormModal.vue')['default']
    PDSFormViewModal: typeof import('./resources/js/components/PDS/View/PDSFormViewModal.vue')['default']
    PersonalDetails: typeof import('./resources/js/components/PDS/FormSections/PersonalDetails.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./resources/js/components/Sidebar/Sidebar.vue')['default']
    ThemeSwitcher: typeof import('./resources/js/FMS/@core/components/ThemeSwitcher.vue')['default']
    Tooltip: typeof import('./resources/js/components/Common/Tooltip.vue')['default']
    TrainingAttended: typeof import('./resources/js/components/PDS/FormSections/TrainingAttended.vue')['default']
    VoluntaryInvolvement: typeof import('./resources/js/components/PDS/FormSections/VoluntaryInvolvement.vue')['default']
    WorkExperience: typeof import('./resources/js/components/PDS/FormSections/WorkExperience.vue')['default']
  }
}
